name: Download NASA Image

on:
  schedule:
    - cron: '0 0 * * *'  # Schedule the workflow to run daily
  workflow_dispatch:  # Allow manual triggering

jobs:
  download_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"

      - name: Download NASA Image and Commit
        run: |
          API_URL="https://api.nasa.gov/planetary/apod"
          API_KEY=${{ secrets.apod }}
          DOWNLOAD_DIR="public"
          IMAGE_FILENAME="apod.jpg"

          # Make request to NASA APOD API using curl
          DATA=$(curl -s "$API_URL?api_key=$API_KEY")

          # Extract relevant information
          IMAGE_URL=$(echo "$DATA" | jq -r '.hdurl')

          # Download the image
          if [ "$IMAGE_URL" != "null" ]; then
            IMAGE_PATH="$DOWNLOAD_DIR/$IMAGE_FILENAME"

            # Download the image and save it to a file
            curl -L -o "$IMAGE_PATH" "$IMAGE_URL"

            # Stage and commit the image
            git add "$IMAGE_PATH"
            git commit -m "Add NASA image for $(date +%Y-%m-%d)"
            echo "NASA image downloaded and committed: $IMAGE_PATH"
          else
            echo "No HD image available."
          fi
